kubelet-arg:
  - container-log-max-files=2
  - container-log-max-size=1Mi
  - config=/etc/rancher/k3s/kubelet-config.yaml

node-ip: "{{ private_ip }},{{ ipv6 }}"
node-external-ip: "{{ public_ip }},{{ ipv6 }}"
